### ISSUE TITLE
Polyglot Sampler not compatible with latest TruffleRuby

### ISSUE THREAD

**Issue by chrisseaton** [oracle/visualvm#382]
```
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
java.lang.NoSuchMethodError: 'void com.oracle.truffle.tools.profiler.CPUSampler.setDelaySamplingUntilNonInternalLangInit(boolean)'
        at org.graalvm.visualvm.sampler.truffle.stagent.Truffle.<init>(Truffle.java:75)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at org.graalvm.visualvm.sampler.truffle.stagent.TruffleJMX.getTruffleInstance(TruffleJMX.java:157)
        at org.graalvm.visualvm.sampler.truffle.stagent.TruffleJMX.agentmain(TruffleJMX.java:69)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:535)
```

**To Reproduce**

Using TruffleRuby as the polyglot language (@eregon can show you the workflow) `jt run -e "loop {}"` in one terminal, then `jt visualvm` in another, try to use Polyglot Sampler.

**Comment by eregon** [comment]
Just to clarify, it's not TruffleRuby-specific at all, the whole Polyglot Sampler no longer works with latest graal, because `CPUSampler.setDelaySamplingUntilNonInternalLangInit` no longer exist.

Would it be possible to have some kind of automated test for this to notice breaking changes earlier?

**Comment by thurka** [comment]
> Would it be possible to have some kind of automated test.

Probably yes. I will try to set up such test.

**Comment by chumer** [comment]
@thurka not sure that is possible, but if you can it would be nice to print a warning or even throw an error if you invoke deprecated methods remotely. We might deprecate and later (after at least 2 releases) remove methods also in the future, that would give us an advance notice of sorts.

**Comment by thurka** [comment]
Fixed in master.

**Comment by thurka** [comment]
Fixed in GraalVM by [7521fe79a](https://github.com/oracle/graal/commit/7521fe79a70fc566b18248a0dde3685725f427c0).

**Comment by chrisseaton** [comment]
Thank you for doing the releasing it into GraalVM - that's really helpful.

**Comment by chrisseaton** [comment]
https://github.com/oracle/graal/commit/1ac0e871e3e4dfc28c0cd68d9da2f75f86c76d17#r77971923

**Comment by eregon** [comment]
As long as VisualVM depends on private stuff and is not tested automatically in the gate this will keep happening.
It is not reasonable for VisualVM to depend on a private field of course, cc @thurka @chumer 

As a workaround until fixed use `--cpusampler=flamegraph` instead.

**Comment by chrisseaton** [comment]
Yes `graalvm-ce-java17-22.2.0-dev` works, thanks very much. I didn't see the fix on `master` here so I assumed it wasn't fixed anywhere - which branch is it on?
